### ISSUE TITLE
Missing menu icon on mobile

### ISSUE THREAD

**Issue by MickayG** [linuxserver/linuxserver.io#7] opened 2018-04-01 23:34 UTC
The menu icon on the top left is missing on Chrome for Android. This includes apps such as Reddit and Google Now(if that's what it's called!)with embedded viewers. 

Chrome version 65.0.3325.109

![screenshot](https://i.imgur.com/vtsIRqS.png)

**Comment by tobbenb** [comment] 2018-04-02 11:05
Yes, we know about it. @JAGFin1 is working on it.

**Comment by JoshStark** [comment] 2018-04-02 21:06
Yep, this is an odd bug which may be to do with the library I'm using for the site. Ongoing investigation for this one.

**Comment by JoshStark** [comment] 2018-04-02 21:07
Closing as this is a partial duplicate of #4

**Closed as completed by JoshStark** 2018-04-02 21:07 UTC
